package com.emailfilter.constants;

public enum CallType {
	GET_ALL_LABEL, CREATE_LABEL_SERVICE, SYNC_LABEL_SERVICE, LABEL_GRID_INFO_SERVICE, EDIT_LABEL_SERVICE,
	SAVE_LABEL_FILTER, LABEL_FILTER_GRID_INFO_SERVICE, EDIT_LABEL_FILTER, SAVE_DELETE_FILTER,
	DELETE_FILTER_GRID_INFO_SERVICE, EDIT_DELETE_FILTER
}
