package com.emailfilter.constants;

public enum FilterLabels {
	CATEGORY_PERSONAL, CATEGORY_SOCIAL, 
	CATEGORY_UPDATES, CATEGORY_FORUMS, CHAT, SENT, INBOX, TRASH,
	CATEGORY_PROMOTIONS, DRAFT, SPAM, STARRED, UNREAD, IMPORTANT
}
